### ISSUE TITLE
Can we run cProfile to see what takes time?

### ISSUE THREAD

**Issue by kais-siala** [tum-ens/renewable-timeseries#11]
Here is the command:
https://stackoverflow.com/questions/8283112/cprofile-saving-data-to-file-causes-jumbles-of-characters

**Comment by HoussameH** [comment]
It seems that c-profile is not really adapted to Multiprocessing. We can however profile each process or module independently.

Find an example of the cprofile summary for the reporting module with only one region:
[cprofile_example.txt](https://github.com/tum-ens/renewable-timeseries/files/3069970/cprofile_example.txt)
