### ISSUE TITLE
Separate regression

### ISSUE THREAD

**Issue by kais-siala** [tum-ens/renewable-timeseries#44]
The regression modules requires that the user reruns the script after moving the files manually anyway. I suggest separating it from "Master.py" and creating another script just for it. The script might still use the assumptions in config.py

**Comment by HoussameH** [comment]
I changed the input folder for the regression. It reads directly the files from the set timestamp folder. I added two parameters to the regression config dictionary, which indicates which hub_heights or orientations are to be used. If the arrays are left empty the function uses all the available hub_heights or orientations for that technology present in the folder
