### ISSUE TITLE
Add timestamp at various steps

### ISSUE THREAD

**Issue by kais-siala** [tum-ens/renewable-timeseries#6]
We can add timestamps before we start and after we finish calculating one region or creating a file.
@HoussameH can you do this please?

**Comment by HoussameH** [comment]
I implemented the timecheck('step') function: displays the function currently running, followed by the step and the current timestamp.
For example:
masking():
timecheck('Saving .mat files')

displays
masking - Saving .mat files - start: 10:13:59:849743
