### ISSUE TITLE
Clean commit history

### ISSUE THREAD

**Issue by kais-siala** [tum-ens/renewable-timeseries#70]
Currently @HoussameH  has almost 2 million lines of code added and deleted... could you identify the exact commit where that happened? It should be in the beginning of May, I think.
We can rebase the history to fix that error. It must be some files that you have forgot to ignore.

**Comment by HoussameH** [comment]
Should this issue be closed ?

**Comment by kais-siala** [comment]
I do not think so.
I think we have to remove the other branches, too...
I will try with one of my branches, and see what happens.
