### ISSUE TITLE
clean EMHIRES

### ISSUE THREAD

**Issue by kais-siala** [tum-ens/renewable-timeseries#78]
instead of copying EMHIRES text files, I would rather read them, clean/filter them, and save the part that is used by the code in the regression folder, similarly to IRENA.

**Comment by HoussameH** [comment]
I need to take a look at IRENA summary, it sounds good though.

**Comment by kais-siala** [comment]
It is really just about reading the text files and using only the years / countries you need.
You already do that. I would only put it in a separate module.
Eventually, we would use the back-up time series for the missing countries at this stage. So the saved csv file should have all the regions that we use, and all the technologies, just for the year we are modeling.

**Comment by kais-siala** [comment]
> 
> 
> I need to take a look at IRENA summary, it sounds good though.

I mean IRENA_regression, not IRENA_summary.
