### ISSUE TITLE
list_regions for regression

### ISSUE THREAD

**Issue by kais-siala** [tum-ens/renewable-timeseries#79]
Right now it is the intersection of EMHIRES and IRENA.
In the future, I want it to be based on the file of IRENA that is saved in the regression folder. If that region is not in EMHIRES, then a back-up time series should be used instead.
Any thoughts on this?

**Comment by HoussameH** [comment]
Good idea

**Comment by HoussameH** [comment]
We could have one model TS for the missing regions. 
Alternatively, we could match the missing regions with the TS of the other regions for which the FLH difference is the minimum. 
What do you think?

**Comment by kais-siala** [comment]
I do not want to overthink it. It could be also some random numbers - a generic time series.
Most importantly, it is saved in the Regression_outputs, so I can edit it manually before I run the regression, if I need too. The shape is anyway less important for me than the FLH constraint.
