### ISSUE TITLE
Pysal 2.0

### ISSUE THREAD

**Issue by kais-siala** [tum-ens/renewable-timeseries#86]
Check where we use Pysal, and how we should rewrite the functions so that we can use Pysal 2.0 instead of v1.14.
Also update the env file.

**Comment by HoussameH** [comment]
I can't find any use of Pysal in renewable-timeseries. It might have been used in zonal_stats.py part of a different script.

**Comment by kais-siala** [comment]
but it is in the environment, isn't it?
can you create an environment without it?
more generally, there are tools that tell you which libraries are actually used.
